# This is a basic workflow to help you get started with Actions

name: CICD Azure Data Factory

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "adf_publish" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ResourceGroup: ADF_DevOps_Demo
  DataFactoryName: ADF-AHCSADemo-

permissions:
      id-token: write
      contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: adf_publish

      # Uploading our artifact from adf_publish branch
      - uses: actions/upload-artifact@v3
        with:
          name: adf-artifact
          path: ADF-AHCSADemo-Dev/
          
  UATDeploy:
    runs-on: ubuntu-latest
    needs: build
    environment: UAT
    steps:
    
      # Downloading the artifact we uploaded earlier
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: adf-artifact

      # Logging in to Azure with OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
          
      # Deploying to UAT environment
      - name: Deploy resources to UAT
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ADF_DevOps_Demo
          dataFactoryName: ADF-AHCSADemo-QA
          armTemplateFile: ARMTemplateForFactory.json
